INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (101, 'SAMSUNG', 8000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (102, 'SAMSUNG', 11000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (103, 'SAMSUNG', 14000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (104, 'SAMSUNG', 17000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (105, 'SAMSUNG', 20000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (106, 'SAMSUNG', 23000, 3, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (107, 'SAMSUNG', 26000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (108, 'SAMSUNG', 29000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (109, 'SAMSUNG', 32000, 3, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (110, 'SAMSUNG', 35000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (111, 'SAMSUNG', 38000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (112, 'SAMSUNG', 41000, 3, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (113, 'SAMSUNG', 44000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (114, 'SAMSUNG', 47000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (115, 'SAMSUNG', 50000, 3, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (116, 'APPLE', 50000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (117, 'APPLE', 53000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (118, 'APPLE', 56000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (119, 'APPLE', 59000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (120, 'APPLE', 62000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (121, 'APPLE', 65000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (122, 'APPLE', 68000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (123, 'APPLE', 70000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (124, 'APPLE', 48000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (125, 'APPLE', 45000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (126, 'APPLE', 38000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (127, 'APPLE', 41000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (128, 'APPLE', 44000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (129, 'APPLE', 47000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (130, 'APPLE', 51000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (131, 'REDMI', 10000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (132, 'REDMI', 15000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (133, 'REDMI', 20000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (134, 'REDMI', 25000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (135, 'REDMI', 30000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (136, 'REDMI', 35000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (137, 'REDMI', 40000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (138, 'REDMI', 45000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (139, 'REDMI', 50000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (140, 'REDMI', 55000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (141, 'REDMI', 65000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (142, 'REDMI', 60000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (143, 'REDMI', 33000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (144, 'REDMI', 38000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (145, 'REDMI', 43000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (146, 'OPPO', 11000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (147, 'OPPO', 14000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (148, 'OPPO', 18000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (149, 'OPPO', 22000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (150, 'OPPO', 26000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (151, 'OPPO', 30000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (152, 'OPPO', 34000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (153, 'OPPO', 38000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (154, 'OPPO', 42000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (155, 'OPPO', 46000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (156, 'OPPO', 50000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (157, 'OPPO', 54000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (158, 'OPPO', 58000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (159, 'OPPO', 62000, 3, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (160, 'OPPO', 8000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (161, 'OPPO', 31000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (162, 'OPPO', 15000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (163, 'OPPO', 19000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (164, 'REALME', 12000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (165, 'REALME', 15000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (166, 'REALME', 19000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (167, 'REALME', 22000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (168, 'REALME', 25000, 3, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (169, 'REALME', 29000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (170, 'REALME', 32000, 5, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (171, 'REALME', 35000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (172, 'REALME', 39000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (173, 'REALME', 42000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (174, 'REALME', 45000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (175, 'REALME', 49000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (176, 'REALME', 52000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (177, 'REALME', 55000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (178, 'REALME', 59000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (179, 'MOTOROLA', 12000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (180, 'MOTOROLA', 15000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (181, 'MOTOROLA', 19000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (182, 'MOTOROLA', 22000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (183, 'MOTOROLA', 35000, 3, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (184, 'MOTOROLA', 49000, 3, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (185, 'MOTOROLA', 32000, 5, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (186, 'MOTOROLA', 45000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (187, 'MOTOROLA', 59000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (188, 'MOTOROLA', 42000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (189, 'MOTOROLA', 35000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (190, 'MOTOROLA', 49000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (191, 'MOTOROLA', 62000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (192, 'MOTOROLA', 15000, 3, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (193, 'MOTOROLA', 29000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (194, 'NOKIA', 12000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (195, 'NOKIA', 15000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (196, 'NOKIA', 19000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (197, 'NOKIA', 22000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (198, 'NOKIA', 25000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (199, 'NOKIA', 29000, 4, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (200, 'NOKIA', 32000, 3, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (201, 'NOKIA', 35000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (202, 'NOKIA', 39000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (203, 'NOKIA', 42000, 5, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (204, 'NOKIA', 45000, 5, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (205, 'NOKIA', 49000, 5, 8);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (206, 'NOKIA', 52000, 4, 4);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (207, 'NOKIA', 55000, 4, 6);

INSERT INTO MOBILES(MOBILE_ID, BRAND_NAME, MOBILE_PRICE, MOBILE_RATING, MOBILE_RAM) VALUES (208, 'NOKIA', 59000, 4, 8);

